---
version: '3'
services:
  http-proxy:
    build:
      context: ./aio
    env_file:
      - .env
    networks:
      - aio-elasticsearch-network
    ports:
      - "127.0.0.1:4500:4500"
    container_name: aio
networks:
  aio-elasticsearch-network:
    name: aio-elasticsearch-network
