name: Deploy cluster

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-staging:
    name: Deploy on staging
    runs-on: ubuntu-latest
    environment:
      name: staging

    timeout-minutes: 15
    strategy:
      matrix:
        include:
          - environment: staging-01
            host: SSH_HOST_STAGING_01
    steps:
      - uses: actions/checkout@v4
      - uses: annuaire-entreprises-data-gouv-fr/github-actions/.github/actions/deploy@v1
        with:
          app-to-deploy: "annuaire-entreprises-search-api"
          app-repository: "https://github.com/annuaire-entreprises-data-gouv-fr/search-api.git"
          app-shortname: "api"
          version: "main"
          environment: "staging"
          ssh-key: ${{ secrets.SSH_MACHINE_USER_PRIVATE_KEY }}
          ssh-host: ${{ secrets[matrix.host] }}
          notify-on-failure: true
          notify-on-success: true
          notify-webhook: ${{ secrets.DEV_EVENT_HOOK }}

  deploy-production:
    name: Deploy on production
    runs-on: ubuntu-latest
    needs: [deploy-staging]
    environment:
      name: production

    timeout-minutes: 15
    strategy:
      matrix:
        include:
          - environment: production-01
            host: SSH_HOST_PRODUCTION_01
          - environment: production-02
            host: SSH_HOST_PRODUCTION_02
          - environment: production-03
            host: SSH_HOST_PRODUCTION_03
    steps:
      - uses: actions/checkout@v4
      - uses: annuaire-entreprises-data-gouv-fr/github-actions/.github/actions/deploy@v1
        with:
          app-to-deploy: "annuaire-entreprises-search-api"
          app-repository: "https://github.com/annuaire-entreprises-data-gouv-fr/search-api.git"
          app-shortname: "api"
          version: "main"
          environment: "production"
          ssh-key: ${{ secrets.SSH_MACHINE_USER_PRIVATE_KEY }}
          ssh-host: ${{ secrets[matrix.host] }}
          notify-on-failure: true
          notify-on-success: true
          notify-webhook: ${{ secrets.DEV_EVENT_HOOK }}
