name: Test Search Algorithm

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  search-tests:
    name: Search Tests
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12.8]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache build
        id: restore-build
        uses: actions/cache@v4
        with:
          path: ${{ env.pythonLocation }}
          key: build-${{ env.pythonLocation }}-${{ matrix.os }}-${{ hashFiles('app/requirements.txt') }}
      - name: Install dependencies
        if: steps.restore-build.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
      - name: Setup Wireguard
        uses: annuaire-entreprises-data-gouv-fr/github-actions/.github/actions/wireguard-up@wireguard/v1
        with:
          wg-config-file: ${{ secrets.WG_CONFIG_FILE }}
      - name: Setup /etc/hosts
        run: |
          DEV_01_HOST=$(echo "${{ secrets.ELASTIC_URL_DEV_1 }}" | sed 's|^https\?://||; s|/$||')
          DEV_02_HOST=$(echo "${{ secrets.ELASTIC_URL_DEV_2 }}" | sed 's|^https\?://||; s|/$||')
          STAGING_HOST=$(echo "${{ secrets.ELASTIC_URL_STAGING }}" | sed 's|^https\?://||; s|/$||')
          sudo bash -c "cat >> /etc/hosts << EOF
          10.0.1.11 $DEV_01_HOST
          10.0.1.12 $DEV_02_HOST
          10.0.1.16 $STAGING_HOST
          EOF"
      - name: Set es endpoint based on PR label
        id: set-es-url
        run: |
          if [[ "${{ contains(github.event.pull_request.labels.*.name, 'test_on_dev_2') }}" == "true" ]]; then
            echo "Targetting Dev 02"
            echo "ELASTIC__USER=${{ secrets.ELASTIC_USER_DEV }}" >> $GITHUB_ENV
            echo "ELASTIC__URL=${{ secrets.ELASTIC_URL_DEV_2 }}" >> $GITHUB_ENV
            echo "ELASTIC__PASSWORD=${{ secrets.ELASTIC_PASSWORD_DEV }}" >> $GITHUB_ENV
          elif [[ "${{ contains(github.event.pull_request.labels.*.name, 'test_on_dev_1') }}" == "true" ]]; then
            echo "Targetting Dev 01"
            echo "ELASTIC__USER=${{ secrets.ELASTIC_USER_DEV }}" >> $GITHUB_ENV
            echo "ELASTIC__URL=${{ secrets.ELASTIC_URL_DEV_1 }}" >> $GITHUB_ENV
            echo "ELASTIC__PASSWORD=${{ secrets.ELASTIC_PASSWORD_DEV }}" >> $GITHUB_ENV
          else
            echo "Targetting Staging"
            echo "ELASTIC__USER=${{ secrets.ELASTIC_USER_STAGING }}" >> $GITHUB_ENV
            echo "ELASTIC__URL=${{ secrets.ELASTIC_URL_STAGING }}" >> $GITHUB_ENV
            echo "ELASTIC__PASSWORD=${{ secrets.ELASTIC_PASSWORD_STAGING }}" >> $GITHUB_ENV
          fi
      - name: Run app and search tests
        run: |
          cd app
          fastapi run &
          echo "********** Application is up **********"
          sleep 10
          pytest tests/search_tests -v -rxX
        env:
          ELASTIC__URL: ${{env.ELASTIC__URL}}
          ELASTIC__USER: ${{ env.ELASTIC__USER }}
          ELASTIC__PASSWORD: ${{ env.ELASTIC__PASSWORD }}
          # dev only: exposes meta.score in payloads
          ENV: dev
          SENTRY__DSN: ${{ secrets.DSN_SENTRY }}
          METADATA__URL_CC_JSON: ${{ secrets.METADATA_URL_CC_JSON }}
          METADATA__URL_UPDATES_JSON: ${{ secrets.METADATA_URL_UPDATES_JSON }}
          APM__URL: ${{ secrets.APM__URL }}
          MATOMO__ID_SITE: ${{ secrets.MATOMO__ID_SITE }}
          MATOMO__TRACKING_URL: ${{ secrets.MATOMO__TRACKING_URL }}
          REDIS__HOST: ${{ secrets.REDIS__HOST }}
          REDIS__PORT: ${{ secrets.REDIS__PORT }}
          REDIS__DATABASE: ${{ secrets.REDIS__DATABASE }}
      - name: Stop Wireguard
        if: always()
        uses: annuaire-entreprises-data-gouv-fr/github-actions/.github/actions/wireguard-down@wireguard/v1
