---
name: Test Search API
on: [push, pull_request]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        python-version: [3.11.1]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache build
        id: restore-build
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: build-${{ env.pythonLocation }}-${{ matrix.os }}-${{ hashFiles('requirements.pip') }}
          restore-keys: build-${{ env.pythonLocation }}-${{ matrix.os }}-${{ hashFiles('requirements.pip') }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r aio/aio-proxy/requirements.pip

  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.11.1]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache build
        id: restore-build
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: build-${{ env.pythonLocation }}-${{ matrix.os }}-${{ hashFiles('requirements.pip') }}
      - name: unit tests
        run: |
          cd aio/aio-proxy/
          pytest aio_proxy/tests/unit_tests -v  

  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: [unit-tests]
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.11.1]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache build
        id: restore-build
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: build-${{ env.pythonLocation }}-${{ matrix.os }}-${{ hashFiles('requirements.pip') }}
      - name: Run app
        run: |
          pip install aiohttp_swagger3
          pip install elastic-apm
          cd aio/aio-proxy/ 
          python -m aio_proxy &
          echo "********** Application is up **********"
          sleep 10
          pytest aio_proxy/tests/e2e_tests -v
        env:
          ELASTIC_URL: ${{secrets.ELASTIC_URL_DEV}}
          ELASTIC_USER: ${{ secrets.ELASTIC_USER_DEV }}
          ELASTIC_PASSWORD: ${{ secrets.ELASTIC_PASSWORD_DEV }}
          ENV: ${{ secrets.ENV_DEV }}
          COLOR_URL: ${{ secrets.COLOR_URL_DEV }}
          DSN_SENTRY: ${{ secrets.DSN_SENTRY }}

  lint-files:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false # Only new or edited files
          VALIDATE_JSCPD: false # Copy/paste detection
          VALIDATE_GITHUB_ACTIONS: false # Due to shellcheck SC2086 issues
          VALIDATE_MARKDOWN: false # Due to multiple headings issue
          VALIDATE_DOCKERFILE_HADOLINT: false
          VALIDATE_HTML: false
          PYTHON_FLAKE8_CONFIG_FILE: .flake8
